Unittest mock
okuda-seminar/client-go pull request #2
Opened 2023-07-23 10:39 UTC by Rwatana

I forgot to make the Pull request. Please check.

2023-07-28 10:13 UTC, nayuta-ai requested changes

2023-07-28 10:13 UTC, nayuta-ai commented on get-resource/src/main.go
> +package main
Remove this file.

2023-07-28 10:13 UTC, nayuta-ai commented on test/src/resource_test.go
> +func TestCreatePod(t *testing.T) {
Test function must test a function.

2023-07-28 10:13 UTC, nayuta-ai commented on test/src/resource_test.go
> +func TestCreatePod(t *testing.T) {
Please divide by two so as to test part and function part.

2023-08-29 05:35 UTC, Rwatana commented
I removed the file and divide them please check.

2023-08-31 06:59 UTC, nayuta-ai requested changes

2023-08-31 06:59 UTC, nayuta-ai commented on get-resource/src/main.go
> +package main
One More, Remove this file because this file covers PR1.

2023-08-31 06:59 UTC, nayuta-ai commented on test/src/resource_test.go
> +package main
Change the directory structure, according to [Go言語でテストコードを書いてみよう](https://note.com/rescuenow_hr/n/n9ed7caf4646d)

2023-08-31 06:59 UTC, nayuta-ai commented on test/src/resource_test.go
> +func TestCreatePod(t *testing.T) {
What function does this file test?

2023-09-11 11:14 UTC, nayuta-ai requested changes

2023-09-11 11:14 UTC, nayuta-ai commented on test/resource_test.go
> +package main
What purpose is this test file?

The purpose of unit test is to check whether target function's behavior is correct or not.

So, I reccomed to separate this file for target function and the corresponding test functioe.

2023-09-11 11:14 UTC, nayuta-ai commented on test/resource_test.go
> +package main
|- mock-practice -- create_pod.go
                               |- create_pod_test.go

2023-09-12 01:31 UTC, Rwatana commented
@nayuta-ai 
I think I have revised the code and the composition of them. Please check my code

2023-09-12 10:15 UTC, nayuta-ai commented
```
|- mock-practice -- create_pod.go
                  |- create_pod_test.go
```

2023-09-13 03:20 UTC, Rwatana commented
@nayuta-ai  Sure, I revised them.
Please check

2023-09-14 13:26 UTC, merged