add the function of CI
okuda-seminar/client-go pull request #3
Opened 2023-08-29 06:11 UTC by Rwatana

Add the CI

2023-08-29 07:48 UTC, Rwatana commented
@nayuta-ai 
## Topic
I think I have added an CI function by using Github actions and test the file.
Please check my code.

## Time
2h

2023-08-30 00:32 UTC, nayuta-ai requested changes

2023-08-30 00:32 UTC, nayuta-ai commented on .github/workflows/ci.yaml
> +  push:
Please change the target on push event.
This implementation only supports this branch, but ci should support all pull request.

2023-08-30 00:32 UTC, nayuta-ai commented on test/src/resource_test.go
> +package main
Divide into test file and src file.

2023-08-30 00:32 UTC, nayuta-ai commented on test/src/resource_test.go
> +package main
This file structure is strange.
test directory contains only test file.

2023-08-30 00:32 UTC, nayuta-ai commented on test/src/resource_test.go
> +package main
src directory contains some implementation, but containing only test file is strange.

2023-08-30 03:36 UTC, Rwatana commented
@nayuta-ai 
## Topic
- I think I changed to work CI in all branches by changing them below. But, I couldn't
confirm them. Does it meet the demands?
```
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
```
- I changed the structure of directory. Please check my change.

2023-08-31 07:05 UTC, nayuta-ai commented on test/src/resource_test.go
> +package main
Refer to https://github.com/okuda-seminar/client-go/pull/2#discussion_r1311178569

2023-08-31 07:05 UTC, nayuta-ai commented
@Rwatana 
Done

2023-08-31 07:09 UTC, nayuta-ai commented
Also, PR3 should only contain CI code. But it contains the test file related to PR2. Because it is strange, so please change.

2023-09-03 01:08 UTC, closed without merging